// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteDiagram(arg1:string):Promise<void>;

export function GetDiagrams():Promise<Array<main.Diagram>>;

export function GetGitHubRepos(arg1:string):Promise<Array<string>>;

export function PollGitHubDeviceFlow(arg1:string,arg2:string):Promise<main.TokenResponse>;

export function SaveDiagram(arg1:main.Diagram):Promise<void>;

export function StartGitHubDeviceFlow(arg1:string):Promise<main.DeviceFlowResponse>;

export function StartProxyServer():Promise<void>;

export function SyncToGitHub(arg1:string,arg2:string,arg3:string):Promise<string>;

export function TestAIConnection(arg1:string,arg2:string):Promise<string>;
