// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteDiagram(arg1) {
  return window['go']['main']['App']['DeleteDiagram'](arg1);
}

export function GetDiagrams() {
  return window['go']['main']['App']['GetDiagrams']();
}

export function GetGitHubRepos(arg1) {
  return window['go']['main']['App']['GetGitHubRepos'](arg1);
}

export function PollGitHubDeviceFlow(arg1, arg2) {
  return window['go']['main']['App']['PollGitHubDeviceFlow'](arg1, arg2);
}

export function SaveDiagram(arg1) {
  return window['go']['main']['App']['SaveDiagram'](arg1);
}

export function StartGitHubDeviceFlow(arg1) {
  return window['go']['main']['App']['StartGitHubDeviceFlow'](arg1);
}

export function StartProxyServer() {
  return window['go']['main']['App']['StartProxyServer']();
}

export function SyncToGitHub(arg1, arg2, arg3) {
  return window['go']['main']['App']['SyncToGitHub'](arg1, arg2, arg3);
}

export function TestAIConnection(arg1, arg2) {
  return window['go']['main']['App']['TestAIConnection'](arg1, arg2);
}
